// src/pages/SignupPage.vue
<template>
    <div id="signup" class="flex justify-center items-center">
        <div class="flex flex-col gap-y-[2rem] bg-blue-400 px-[6rem] py-[4rem] rounded-md">
            <h1>Sign Up</h1>
            <form @submit.prevent="userStore.signup(formData)">
                <div>
                    <label for="email">Email:</label>
                    <input type="email" id="email" v-model="formData.email" />
                </div>
                <div>
                    <label for="password">Password:</label>
                    <input type="password" id="password" v-model="formData.password" />
                </div>
                <div>
                    <label for="confirmPassword">Confirm Password:</label>
                    <input type="password" id="confirmPassword" v-model="formData.confirmPassword" />
                </div>
                <button type="submit">Sign Up</button>
            </form>
        </div>
    </div>
</template>

<script setup>
import { ref } from 'vue';
import { useUserStore } from '../stores/user'

// Store
const userStore = useUserStore();

// State
const formData = ref({
    email: '',
    password: '',
    confirmPassword: '',
});
</script>

// src/pages/SignupPage.jsx
import React from 'react'

const SignupPage = () => {
  return (
    <div id="signup" className="flex justify-center items-center">
      <div className="flex flex-col gap-y-[2rem] bg-blue-400 px-[6rem] py-[4rem] rounded-md">
        <h1>Sign Up</h1>
        <form className="flex-col-1">
          <div className="flex-col-05">
            <label htmlFor="email">Email:</label>
            <input type="email" id="email" v-model="formData.email" />
          </div>
          <div className="flex-col-05">
            <label htmlFor="password">Password:</label>
            <input type="password" id="password" v-model="formData.password" />
          </div>
          <div className="flex-col-05">
            <label htmlFor="confirmPassword">Confirm Password:</label>
            <input type="password" id="confirmPassword" v-model="formData.confirmPassword" />
          </div>
          <button className="mt-[1rem] py-[0.5rem] hover:bg-blue-100/40 border rounded-md" type="submit">Submit</button>
        </form>
      </div>
    </div>
  )
}

export default SignupPage
