// src/components/Header.vue
<template>
    <header class="flex items-center py-[2rem]">
        <div class="container flex justify-between">
            <router-link to="/">Recipe App</router-link>
            <nav>
                <div class="account">
                    <router-link v-if="user?.email" to="/dashboard">{{ user.email }}</router-link>
                    <div v-if="isAuthenticated" @click="userStore.logout">Logout</div>
                    <router-link v-else-if="route.path !== '/login'" to="/login">Login</router-link>
                </div>
            </nav>
        </div>
    </header>
</template>
<script setup>
import { storeToRefs } from 'pinia';
import { useRoute } from 'vue-router';
import { useUserStore } from '../stores/user'

const route = useRoute();
const userStore = useUserStore();

// State
const { isAuthenticated, user } = storeToRefs(userStore);
</script>

// src/components/Header.jsx
import React from 'react'
import { useAuth } from '@/contexts/AuthContext';

import { Link } from 'react-router-dom';

const Header = () => {
    const { logOut, isLoggedIn, user } = useAuth();

    return (
        <header className='py-[2rem]'>
            <div className="container flex justify-between">
                <Link to="/">
                    <h1 className='text-2xl'>Al Dente</h1>
                </Link>
                <div className="flex items-center gap-x-[2rem]">
                    {isLoggedIn && <p>{user.email}</p>}
                    <nav className="flex gap-[1rem] items-center">
                        {isLoggedIn && <Link to="/dashboard">Dashboard</Link>}
                        {isLoggedIn ? <button onClick={logOut}>Log out</button> : <Link to="/login">Login</Link>}
                    </nav>
                </div>
            </div >
        </header >
    )
}

export default Header;
